### ISSUE TITLE
State of the art: log4cats

### ISSUE THREAD

**Issue by diesalbla** [pure4s/logger4s#8]
Good evening. 

I have taken a look at the current code in this project. From what I have seen of the current code, its goal is to create a set of tagless logging algebras, or traits parameterised on an effect-type `F[_]`, to support the common logging operations, based on the functional Scala libraries [cats](https://typelevel.org/cats/) and [cats-effect](https://typelevel.org/cats-effect/).  

There is another library, [log4cats](https://github.com/ChristopherDavenport/log4cats), which is already pursuing those goals. It is being developed by  . Its being developed  Its latest release provides such features as:
- Integrations with logger systems other than `slf4j`, such as `scribe` and `log4s`.
- Integrations with type classes of `cats`. 
- Support for structured logging. 
- A [microsite](https://christopherdavenport.github.io/log4cats/), something that is pending work for this project #3.

It is my most humble opinion that the `log4cats` project already is in a more mature state of development than the current one. The goal of this issue is to make the the developers behind this project, such as @llfrometa89, aware of the existence of `log4cats`, so that they may take it into account when considering the development of the current project.

Kind regards.

**Comment by llfrometa89** [comment]
Hi Diego,
Thank you so much for your comments. If I have some knowledge of  log4cats library, I took some ideas to develop logger4s. I decided to implement some things adapted to my taste, everyone who is interested in contributing and using it will be always welcome.

King Regards
